/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 earth.gltf 
Author: denis_cliofas (https://sketchfab.com/denis_cliofas)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/earth-3684eb40fb7e42208089874e6286b9e9
Title: Earth
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

function Earth(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/earth.gltf");
  // const { actions } = useAnimations(animations, group);
  return (
    // eslint-disable-next-line react/no-unknown-property,react/jsx-props-no-spreading
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          /* eslint-disable-next-line react/no-unknown-property */
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.002}
        >
          <group
            name="fc09fa6deb6c45f687e724438fed81adfbx"
            /* eslint-disable-next-line react/no-unknown-property */
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="Earth"
                  /* eslint-disable-next-line react/no-unknown-property */
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={57.393}
                >
                  <mesh
                    name="Earth_Earth_0"
                    /* eslint-disable-next-line react/no-unknown-property */
                    geometry={nodes.Earth_Earth_0.geometry}
                    /* eslint-disable-next-line react/no-unknown-property */
                    material={materials.Earth}
                  />
                  <mesh
                    name="Earth_Earth_0_1"
                    /* eslint-disable-next-line react/no-unknown-property */
                    geometry={nodes.Earth_Earth_0_1.geometry}
                    /* eslint-disable-next-line react/no-unknown-property */
                    material={materials.Earth}
                  />
                  <mesh
                    name="Earth_Earth_0_2"
                    /* eslint-disable-next-line react/no-unknown-property */
                    geometry={nodes.Earth_Earth_0_2.geometry}
                    /* eslint-disable-next-line react/no-unknown-property */
                    material={materials.Earth}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/earth.gltf");

export default Earth;
