/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 jupiter.gltf 
Author: SunnyChen753/SW fan (https://sketchfab.com/sunnychen753)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/jupiter-37271436312745c1ae375a4c4f874355
Title: Jupiter
*/

import React, { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";

function Jupiter(props) {
  const { nodes, materials } = useGLTF("/jupiter.gltf");
  const meshRef = useRef();

  useEffect(() => {
    if (meshRef.current) {
      // Centrer la géométrie
      const { geometry } = meshRef.current;
      geometry.computeBoundingBox();
      geometry.center();
    }
  }, []);

  return (
    // eslint-disable-next-line react/no-unknown-property,react/jsx-props-no-spreading
    <group {...props} dispose={null}>
      <mesh
        ref={meshRef}
        /* eslint-disable-next-line react/no-unknown-property */
        geometry={nodes.Object_2.geometry}
        /* eslint-disable-next-line react/no-unknown-property */
        material={materials.jupiter}
        /* eslint-disable-next-line react/no-unknown-property */
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/jupiter.gltf");

export default Jupiter;
