/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 mars.gltf 
Author: JanesBT (https://sketchfab.com/JanesBt)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mars-6f9ebc64e6c74068a8412a7dd74dfb96
Title: Mars
*/

import React, { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";

function Mars(props) {
  const { nodes, materials } = useGLTF("/mars.gltf");
  const meshRef = useRef();

  useEffect(() => {
    if (meshRef.current) {
      // Centrer la géométrie
      const { geometry } = meshRef.current;
      geometry.computeBoundingBox();
      geometry.center();
    }
  }, []);

  return (
    // eslint-disable-next-line react/no-unknown-property,react/jsx-props-no-spreading
    <group {...props} dispose={null}>
      <mesh
        ref={meshRef}
        /* eslint-disable-next-line react/no-unknown-property */
        geometry={nodes.Object_2.geometry}
        /* eslint-disable-next-line react/no-unknown-property */
        material={materials["Material.001"]}
        /* eslint-disable-next-line react/no-unknown-property */
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/mars.gltf");

export default Mars;
