/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 neptune.gltf 
Author: kongle (https://sketchfab.com/minecraftnorge)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/neptune-8c6dc96f47ab4d798a1cb2d827da3fbe
Title: Neptune
*/

import React, { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";

export function Neptune(props) {
  const { nodes, materials } = useGLTF("/neptune.gltf");
  const meshRef = useRef();

  useEffect(() => {
    if (meshRef.current) {
      // Centrer la géométrie
      const { geometry } = meshRef.current;
      geometry.computeBoundingBox();
      geometry.center();
    }
  }, []);

  return (
    // eslint-disable-next-line react/no-unknown-property,react/jsx-props-no-spreading
    <group {...props} dispose={null}>
      <mesh
        ref={meshRef}
        /* eslint-disable-next-line react/no-unknown-property */
        geometry={nodes.Object_2.geometry}
        /* eslint-disable-next-line react/no-unknown-property */
        material={materials.neptune}
        /* eslint-disable-next-line react/no-unknown-property */
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/neptune.gltf");

export default Neptune;
