/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 uranus.gltf 
Author: kongle (https://sketchfab.com/minecraftnorge)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/uranus-b488282fa28344009fa8c8cdb3384456
Title: Uranus
*/

import React, { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";

function Uranus(props) {
  const { nodes, materials } = useGLTF("/uranus.gltf");
  const meshRef = useRef();

  useEffect(() => {
    if (meshRef.current) {
      // Centrer la géométrie
      const { geometry } = meshRef.current;
      geometry.computeBoundingBox();
      geometry.center();
    }
  }, []);

  return (
    // eslint-disable-next-line react/no-unknown-property,react/jsx-props-no-spreading
    <group {...props} dispose={null}>
      <mesh
        ref={meshRef}
        /* eslint-disable-next-line react/no-unknown-property */
        geometry={nodes.Object_3.geometry}
        /* eslint-disable-next-line react/no-unknown-property */
        material={materials.uranus}
      />
    </group>
  );
}

useGLTF.preload("/uranus.gltf");

export default Uranus;
