/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 venus.gltf 
Author: Anthony Yanez (https://sketchfab.com/paulyanez)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/venus-3fc4363f27f8470d9225048845c53599
Title: Venus
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

function Venus(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/venus.gltf");

  return (
    // eslint-disable-next-line react/jsx-props-no-spreading,react/no-unknown-property
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        {/* eslint-disable-next-line react/no-unknown-property */}
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          {/* eslint-disable-next-line react/no-unknown-property */}
          <group name="VenusFBX" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                {/* eslint-disable-next-line react/no-unknown-property */}
                <group name="Clouds" rotation={[-1.833, 0, 0]} scale={0.815}>
                  <mesh
                    name="Clouds_01_-_Default_0"
                    /* eslint-disable-next-line react/no-unknown-property */
                    geometry={nodes["Clouds_01_-_Default_0"].geometry}
                    /* eslint-disable-next-line react/no-unknown-property */
                    material={materials["01_-_Default"]}
                  />
                </group>
                {/* eslint-disable-next-line react/no-unknown-property */}
                <group name="Venus" rotation={[-1.833, 0, 0]} scale={0.79}>
                  <mesh
                    name="Venus_07_-_Default_0"
                    /* eslint-disable-next-line react/no-unknown-property */
                    geometry={nodes["Venus_07_-_Default_0"].geometry}
                    /* eslint-disable-next-line react/no-unknown-property */
                    material={materials["07_-_Default"]}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/venus.gltf");

export default Venus;
